### ISSUE TITLE
How to mock firebase-ruby with VCR

### ISSUE THREAD

**Issue by aosyatnik** [oscardelben/firebase-ruby#86]
Good day.
I'm trying to mock up firebase requests with VCR. With old api it used to work as following:

```yml
- request:
    method: get
    uri: https://test-database.firebaseio.com/alerts.json?auth=foobar
    body:
      encoding: UTF-8
      string: ''
    headers:
      User-Agent:
      - HTTPClient/1.0 (2.8.3, ruby 2.3.1 (2016-04-26))
      Accept:
      - "*/*"
      Date:
      - Tue, 12 Dec 2017 05:00:00 GMT
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Wed, 17 Jan 2018 11:20:04 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '4'
      Connection:
      - keep-alive
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-cache
      Strict-Transport-Security:
      - max-age=31556926; includeSubDomains; preload
    body:
      encoding: UTF-8
      string: 'null'
    http_version:
  recorded_at: Tue, 12 Dec 2017 05:00:00 GMT
```

But now, with new API it makes additional request to `https://www.googleapis.com/oauth2/v3/token` and I have no idea how to mock this request. I've tried as following:
```yml
- request:
    method: post
    uri: https://www.googleapis.com/oauth2/v3/token
    body:
      encoding: UTF-8
      string: ''
    headers:
      User-Agent:
      - HTTPClient/1.0 (2.8.3, ruby 2.3.1 (2016-04-26))
      Accept:
      - "*/*"
      Date:
      - Tue, 12 Dec 2017 05:00:00 GMT
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - GSE
      Date:
      - Wed, 17 Jan 2018 11:20:08 GMT
      Content-Type:
      - application/json; charset=UTF-8
      Content-Length:
      - '131'
      Connection:
      - keep-alive
      Access-Control-Allow-Origin:
      - "*"
      Cache-Control:
      - no-cache
      Strict-Transport-Security:
      - max-age=31556926; includeSubDomains; preload
    body:
      encoding: UTF-8
      ????? WHAT SHOULD BE THERE ????? string: '{"kind":"identitytoolkit#VerifyCustomTokenResponse","idToken":"foo", "refreshToken": "foo", "expiresIn": "3600", "isNewUser": true}' 
    http_version:
  recorded_at: Tue, 12 Dec 2017 05:00:00 GMT
```
But it doesn't work. In terminal I can see, that it's failing somewhere on 30 row:
![image](https://user-images.githubusercontent.com/8158404/36315468-1c14473a-1338-11e8-887d-023b7ad1edfd.png)

I assume that response json, that I wrote is incorrect. What is expected output?
Could you, please, give me some tips how can I mock up firebase calls?
Thank you and I'm sorry if it's kind of stupid question.

Best wishes!
